function phonegapdemo(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',kc='.cache.html',$='/',Zb='16FA7BE9EF79BA988F8EA7488A4E1A7C',$b='172478D048A7942B06BD09190869AEB7',_b='20938C557521C53B7DBEE90605CDECD3',ac='26853301C064E1A074223DAC91AF45F2',bc='3C00C06C544E02CBE862EE80E9F3D83C',cc='5D1D607D2842932E15D6742FB4FF4E0C',dc='78ECA35F6B2C38735081BE570D9404AB',ec='9569A4776DC41F27FD8A36455A80DC22',jc=':',nb='::',mc='<script defer="defer">phonegapdemo.onInjectionDone(\'phonegapdemo\')<\/script>',gb='<script id="',qb='=',Z='?',fc='ACEA6A53EC1A469FE1F1A64B5307F19C',Mb='ActiveXObject',gc='BC6DEE07026D17A2EC833F3A8455A73B',sb='Bad handler "',hc='CA15FBC417ECB605BE6853E8873BD9A8',Nb='ChromeTab.ChromeFrame',lc='DOMContentLoaded',ic='F6B54A3035CC5BD1912B6BE5B3D40250',ib='SCRIPT',fb='__gwt_marker_phonegapdemo',Bb='android',jb='base',bb='baseUrl',S='begin',Eb='blackberry',R='bootstrap',Lb='chromeframe',ab='clear.cache.gif',pb='content',X='end',Fb='file://',Tb='gecko',Ub='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',Xb='hosted.html?phonegapdemo',Sb='ie6',Rb='ie8',Qb='ie9',wb='iframe',_='img',Cb='ipad',Db='iphone',xb="javascript:''",Wb='loadExternalRefs',kb='meta',zb='moduleRequested',W='moduleStartup',Pb='msie',lb='name',Hb='no',Jb='opera',Ab='phonegap.env',P='phonegapdemo',db='phonegapdemo.nocache.js',mb='phonegapdemo::',yb='position:absolute;width:0;height:0;border:none',Ob='safari',cb='script',Yb='selectingPermutation',Q='startup',eb='undefined',Vb='unknown',Ib='user.agent',Kb='webkit',Gb='yes';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}phonegapdemo=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1||(a.indexOf(Cb)!=-1||(a.indexOf(Db)!=-1||a.indexOf(Eb)!=-1))){var b=document.location.href;if(b.indexOf(Fb)===0){return Gb}}return Hb}};u[Ab]={no:0,yes:1};v[Ib]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Jb)!=-1}())return Jb;if(function(){return c.indexOf(Kb)!=-1||function(){if(c.indexOf(Lb)!=-1){return true}if(typeof window[Mb]!=eb){try{var b=new ActiveXObject(Nb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Ob;if(function(){return c.indexOf(Pb)!=-1&&m.documentMode>=9}())return Qb;if(function(){return c.indexOf(Pb)!=-1&&m.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Sb;if(function(){return c.indexOf(Tb)!=-1}())return Ub;return Vb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};phonegapdemo.onScriptLoad=function(){if(H){q=true;B()}};phonegapdemo.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Wb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Xb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Yb});if(!A()){try{F([Gb,Sb],Zb);F([Gb,Rb],$b);F([Hb,Ob],_b);F([Gb,Ub],ac);F([Gb,Ob],bc);F([Hb,Sb],cc);F([Gb,Qb],dc);F([Hb,Jb],ec);F([Hb,Rb],fc);F([Hb,Ub],gc);F([Hb,Qb],hc);F([Gb,Jb],ic);J=w[G(Ab)][G(Ib)];var L=J.indexOf(jc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+kc}catch(a){return}}var M;function N(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(lc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(lc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Wb,millis:(new Date).getTime(),type:S});m.write(mc)}
phonegapdemo();